#!/bin/bash

set -o errexit
set -o xtrace

declare -A SERVICES=(
    ["md"]="deadlock_holder deadlock_requestor defrag_innodb extra_innodb onlineddl_innodb sb_aria sb_innodb sb_innodb_spike"
)

ROOT_DIR=$(realpath "$(dirname $0)")

remove_all() {
    local SOCKET_NAME=$1
    pushd $ROOT_DIR/loader
        for LOADER in $(ls); do
            if [ -e "/etc/systemd/system/pmm-${LOADER}-${SOCKET_NAME}.service" ]; then
                systemctl --no-reload disable "pmm-${LOADER}-${SOCKET_NAME}" > /dev/null 2>&1 || :
                systemctl stop "pmm-${LOADER}-${SOCKET_NAME}" > /dev/null 2>&1 || :
            fi
        done
    popd
}

create_loader() {
    local LOADER=$1
    local SOCKET_PATH=$2
    local SOCKET_NAME=$(basename $SOCKET_PATH | sed -e 's/.sock$//')
    cat - <<-EOF >/etc/systemd/system/pmm-${LOADER}-${SOCKET_NAME}.service
		[Unit]
		Description=PMM Loader ${LOADER} for ${SOCKET_NAME} socket

		[Service]
		StartLimitInterval=5
		StartLimitBurst=10
		ExecStart=$ROOT_DIR/loader/${LOADER} $SOCKET_PATH
		Restart=always
		RestartSec=120

		[Install]
		WantedBy=multi-user.target
	EOF
    systemctl preset "pmm-${LOADER}-${SOCKET_NAME}"
    systemctl start "pmm-${LOADER}-${SOCKET_NAME}"
}

main() {
    local TYPE=$1
    local SOCKET_PATH=$2
    local SOCKET_NAME=$(basename $SOCKET_PATH | sed -e 's/.sock$//')

    if [[ -z "$TYPE" ]] || [[ -z "${SERVICES[$TYPE]}" ]]; then
        echo "unknown server type"
        echo "usage: $0 {ps|pxc|mo|ms|md} /path/to/service.socket"
        exit 1
    fi
    if [[ -z "$SOCKET_PATH" ]] || [[ ! -S "$SOCKET_PATH" ]]; then
        echo "cannot find $SOCKET_PATH socket"
        echo "usage: $0 {ps|pxc|mo|ms|md} /path/to/service.socket"
        exit 1
    fi

    remove_all "$SOCKET_NAME"

    mysql -S "${SOCKET_PATH}" < $ROOT_DIR/grants.sql
    for LOADER in ${SERVICES[$TYPE]}; do
        create_loader "$LOADER" "$SOCKET_PATH" "$SOCKET_NAME"
    done
}

main "$@"
exit 0
