#!/bin/sh

set -o xtrace

DBNAME=aria
ENGINE=aria
TEST=/usr/share/sysbench/oltp_read_write.lua
SOCKET=${1:-/var/lib/mysql/mysql.sock}

mysql \
    --socket=$SOCKET \
    --user=sbtest \
    --password=sbtest \
    -e "CREATE DATABASE IF NOT EXISTS $DBNAME"
sysbench \
    --db-driver=mysql \
    --mysql-socket=$SOCKET \
    --mysql-user=sbtest \
    --mysql-password=sbtest \
    --mysql-db=$DBNAME \
    --mysql-table-engine=$ENGINE \
    $TEST \
    prepare
mysql \
    --socket=$SOCKET \
    --user=sbtest \
    --password=sbtest \
    --database=$DBNAME \
    -e "ALTER TABLE sbtest1 ENGINE=aria, TRANSACTIONAL=1"

while true; do
    sysbench \
        --rate=1 \
        --threads=1 \
        --report-interval=1 \
        --time=0 \
        --events=0 \
        --rand-type=pareto \
        --db-driver=mysql \
        --mysql-socket=$SOCKET \
        --mysql-user=sbtest \
        --mysql-password=sbtest \
        --mysql-db=$DBNAME \
        --mysql-table-engine=$ENGINE \
        --point_selects=1 \
        $TEST \
        run
    sleep 5
done
