#!/bin/sh

set -o xtrace

DBNAME=innodb
SOCKET=${1:-/var/lib/mysql/mysql.sock}

mysql \
    --socket=$SOCKET \
    --user=sbtest \
    --password=sbtest \
    --database=${DBNAME} \
    -e "
        DROP TABLE IF EXISTS deadlock;
        CREATE TABLE deadlock (
            pk int unsigned auto_increment primary key
        ) ENGINE=innodb;
        INSERT INTO deadlock (pk) VALUES (1);
    "

while true; do
    mysql \
        --socket=$SOCKET \
        --user=sbtest \
        --password=sbtest \
        --database=${DBNAME} \
        -e "
            START TRANSACTION;
            SELECT * FROM deadlock WHERE pk = 1 LOCK IN SHARE MODE;
            SELECT SLEEP(1);
            DELETE FROM deadlock where pk = 1;
        "
done
