#!/bin/sh

set -o xtrace

DBNAME=deadlock
SOCKET=${1:-/var/lib/mysql/mysql.sock}

while true; do
    mysql \
        --socket=$SOCKET \
        --user=sbtest \
        --password=sbtest \
        --database=${DBNAME} \
        -e "
            START TRANSACTION;
            DELETE FROM deadlock where pk = 1;
        "
done
