#!/bin/sh

set -o xtrace

DBNAME=innodb
SOCKET=${1:-/var/lib/mysql/mysql.sock}

while true; do
    mysql \
        --socket=$SOCKET \
        --user=sbtest \
        --password=sbtest \
        --database=${DBNAME} \
        -e "
            OPTIMIZE TABLE sbtest1;
        "
    sleep 5
done
