#!/bin/sh

set -o xtrace

DBNAME=innodb
ENGINE=innodb
TABLE_SIZE=100000000
TEST=/usr/share/sysbench/tests/include/oltp_legacy/update_index.lua
SOCKET=${1:-/var/lib/mysql/mysql.sock}

while true; do
    sysbench \
        --threads=64 \
        --report-interval=10 \
        --time=300 \
        --events=0 \
        --rand-type=pareto \
        --db-driver=mysql \
        --mysql-socket=$SOCKET \
        --mysql-user=sbtest \
        --mysql-password=sbtest \
        --mysql-db=$DBNAME \
        --mysql-table-engine=$ENGINE \
        --oltp-reconnect \
        --oltp-table-size=$TABLE_SIZE \
        $TEST \
        run
    sleep 3300
done
