#!/bin/sh

set -o xtrace

DBNAME=innodb
ENGINE=innodb
TABLE_SIZE=100000000
TEST=/usr/share/sysbench/tests/include/oltp_legacy/oltp.lua
SOCKET=${1:-/var/lib/mysql/mysql.sock}

if [ -S "$SOCKET" ]; then
    CONNECTION="--socket=$SOCKET"
    SB_CONNECTION="--mysql-socket=$SOCKET"
else
    CONNECTION="--host=$SOCKET"
    SB_CONNECTION="--mysql-host=$SOCKET"
fi

mysql \
    $CONNECTION \
    --user=sbtest \
    --password=sbtest \
    -e "CREATE DATABASE IF NOT EXISTS $DBNAME"
sysbench \
    $SB_CONNECTION \
    --db-driver=mysql \
    --mysql-user=sbtest \
    --mysql-password=sbtest \
    --mysql-db=$DBNAME \
    --mysql-table-engine=$ENGINE \
    --oltp-table-size=$TABLE_SIZE \
    $TEST \
    prepare

while true; do
    sysbench \
        $SB_CONNECTION \
        --rate=1 \
        --threads=1 \
        --report-interval=10 \
        --time=0 \
        --events=0 \
        --rand-type=pareto \
        --db-driver=mysql \
        --mysql-user=sbtest \
        --mysql-password=sbtest \
        --mysql-db=$DBNAME \
        --mysql-table-engine=$ENGINE \
        --oltp-reconnect \
        --oltp-table-size=$TABLE_SIZE \
        $TEST \
        run
    sleep 60
done
