#!/bin/sh

set -o xtrace
DBNAME=postgres
USER=postgres
PASS=postgres
HOST=$1

sysbench \
    --db-driver=pgsql \
    --pgsql-host=$HOST \
    --pgsql-user=$USER \
    --pgsql-password=$PASS \
    --pgsql-db=$DBNAME \
    /usr/share/sysbench/oltp_read_write.lua \
    prepare

while true; do
    sysbench \
        --rate=1 \
        --threads=1 \
        --report-interval=10 \
        --time=0 \
        --events=0 \
        --rand-type=pareto \
        --db-driver=pgsql \
        --pgsql-host=$HOST \
        --pgsql-user=$USER \
        --pgsql-password=$PASS \
        --pgsql-db=$DBNAME \
        /usr/share/sysbench/oltp_read_write.lua \
        run
    sleep 60
done
