#!/bin/sh

set -o xtrace

DBNAME=innodb
SOCKET=${1:-/var/lib/mysql/mysql.sock}

mysql \
    --socket=$SOCKET \
    --user=sbtest \
    --password=sbtest \
    -e "CREATE DATABASE IF NOT EXISTS $DBNAME"
sysbench \
    --db-driver=mysql \
    --mysql-socket=$SOCKET \
    --mysql-user=sbtest \
    --mysql-password=sbtest \
    --mysql-db=$DBNAME \
    /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua \
    cleanup
sysbench \
    --db-driver=mysql \
    --mysql-socket=$SOCKET \
    --mysql-user=sbtest \
    --mysql-password=sbtest \
    --mysql-db=$DBNAME \
    /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua \
    prepare

while true; do
    sysbench \
        --rate=20 \
        --threads=64 \
        --report-interval=10 \
        --time=0 \
        --events=0 \
        --rand-type=pareto \
        --oltp-table-size=100000000 \
        --db-driver=mysql \
        --mysql-socket=$SOCKET \
        --mysql-user=sbtest \
        --mysql-password=sbtest \
        --mysql-db=$DBNAME \
        --oltp-reconnect \
        /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua \
        run
    sleep 60
done
