#!/bin/sh

set -o xtrace

DBNAME=innodb
SOCKET=${1:-/var/lib/mysql/mysql.sock}

while true; do
    sysbench \
        --threads=64 \
        --report-interval=10 \
        --time=300 \
        --events=0 \
        --rand-type=pareto \
        --oltp-table-size=100000000 \
        --db-driver=mysql \
        --mysql-socket=$SOCKET \
        --mysql-user=sbtest \
        --mysql-password=sbtest \
        --mysql-db=$DBNAME \
        --oltp-reconnect \
        /usr/share/sysbench/tests/include/oltp_legacy/update_index.lua \
        run
    sleep 3300
done
