#!/bin/sh

set -o xtrace

DBNAME=small
SOCKET=${1:-/var/lib/mysql/mysql.sock}

while true; do
    RND=$(( RANDOM % 7000 * 10000 ))
    mysql \
        --socket=$SOCKET \
        --user=sbtest \
        --password=sbtest \
        --database=${DBNAME} \
        -e "
            UPDATE sbtest1
            SET    k=$RND
        "
    sleep 950
done
