#!/bin/sh

set -o xtrace

DBNAME=small
SOCKET=${1:-/var/lib/mysql/mysql.sock}

while true; do
    mysql \
        --socket=$SOCKET \
        --user=sbtest \
        --password=sbtest \
        --database=${DBNAME} \
        -e "
            UPDATE sbtest1
            SET    k=rand()*3
            WHERE  id=5
        "
    sleep 550
done
